name: Python Package

on:
    workflow_run:
        workflows: ["Tests"]
        types:
            - completed

jobs:
    build_package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/build

    publish_package:
        needs: build_package
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:  
            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                name: python-package-distributions
                path: dist/
            - uses: pypa/gh-action-pypi-publish@release/v1
        permissions:
            id-token: write
        environment:
            name: pypi
            url: https://pypi.org/p/cvmatrix

    github_release:
        needs: publish_package
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/release